version: "2"

services:

  lb:
    image: haproxy:1.7
    ports:
      - "80:80"
    networks:
      LAN1:
        ipv4_address: 10.0.1.1
      LAN2:
        ipv4_address: 10.0.2.1
  s1:
    build: ./apacheServer/
    ports:
      - "80:80"
    command: echo s1 > /var/www/html/index.html
    networks:
      LAN2:
        ipv4_address: 10.0.2.11

  s2:
    build: ./apacheServer/
    ports:
      - "80:80"
    command: echo s2 > /var/www/html/index.html
    networks:
      LAN2:
        ipv4_address: 10.0.2.12
  s3:
    build: ./apacheServer/
    ports:
      - "80:80"
    command: echo s3 > /var/www/html/index.html
    networks:
      LAN2:
        ipv4_address: 10.0.2.13
  s4:
    build: ./apacheServer/
    ports:
      - "80:80"
    command: echo s4 > /var/www/html/index.html
    networks:
      LAN2:
        ipv4_address: 10.0.2.14
  s5:
    build: ./apacheServer/
    ports:
      - "80:80"
    command: echo s5 > /var/www/html/index.html
    networks:
      LAN2:
        ipv4_address: 10.0.2.15

  c1:
    image: ubuntu:16.04
    networks:
      LAN1:
        ipv4_address: 10.0.1.2

networks:
  LAN1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
  LAN2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1